# Generated by Django 3.1 on 2020-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='noticias/imagens'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
